version: '3'
services:
  api:
    build:
      context: '.'
      dockerfile: './.image/api.Dockerfile'
    volumes:
      - './src:/go/src'
  gopher:
    image: golang:1.20
    working_dir: /go/src
    volumes:
      - ./src:/go/src
      - ./cover:/go/cover
  api-spec:
    build:
      context: '.'
      dockerfile: './.image/api-spec.Dockerfile'
    volumes:
      - './documents/open-api:/data'
      - ./spec:/spec
  spec-preview:
    image: 'redocly/redoc'
    volumes:
      - './documents/open-api:/usr/share/nginx/html/swagger'
    environment:
      SPEC_URL: './swagger/mysrtafes-api.yml'
      PORT: 8080
